# Generated by Django 4.2.3 on 2023-07-13 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import game.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                ("text", models.TextField(max_length=666)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("MULTIPLE", "Multiple"),
                            ("TRUEFALSE", "True or False"),
                        ],
                        default="MULTIPLE",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("UNASSIGNED", "Unassigned"),
                            ("EASY", "Easy"),
                            ("MEDIUM", "Medium"),
                            ("HARD", "Hard"),
                        ],
                        default="UNASSIGNED",
                        max_length=20,
                    ),
                ),
                (
                    "asked_to",
                    models.ManyToManyField(
                        related_name="questions_asked", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "correct_option",
                    models.ForeignKey(
                        default=game.models.Option.get_default_pk,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="questions_correct",
                        to="game.option",
                    ),
                ),
                (
                    "falls_under",
                    models.ManyToManyField(
                        related_name="all_questions", to="game.category"
                    ),
                ),
                (
                    "incorrect_options",
                    models.ManyToManyField(
                        related_name="related_questions", to="game.option"
                    ),
                ),
            ],
            options={
                "verbose_name": "question",
                "verbose_name_plural": "questions",
            },
        ),
    ]
