# Generated by Django 4.2.3 on 2023-07-14 09:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lifeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("name", models.CharField(max_length=81)),
                ("description", models.TextField(max_length=1000)),
            ],
            options={
                "verbose_name": "lifeline",
                "verbose_name_plural": "lifelines",
            },
        ),
        migrations.AlterField(
            model_name="session",
            name="session_id",
            field=models.CharField(
                default="2iEy5mSl",
                editable=False,
                max_length=8,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="left_lifelines",
            field=models.ManyToManyField(
                related_name="sessions_unused", to="game.lifeline"
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="used_lifelines",
            field=models.ManyToManyField(
                related_name="sessions_used", to="game.lifeline"
            ),
        ),
    ]
