# Generated by Django 4.2.3 on 2023-07-13 13:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import game.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("game", "0002_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_chosen",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.question"
                    ),
                ),
            ],
            options={
                "verbose_name": "ordering of question in session",
                "verbose_name_plural": "ordering of questions in session",
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "session_id",
                    models.CharField(
                        default="0A28eBPV",
                        editable=False,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "score",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100000000),
                        ],
                        verbose_name="Money Won",
                    ),
                ),
                (
                    "correct_qns",
                    models.ManyToManyField(
                        related_name="sessions_correct_in", to="game.question"
                    ),
                ),
                (
                    "current_level",
                    models.ForeignKey(
                        default=game.models.Level.get_default_pk,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="sessions_currently",
                        to="game.level",
                    ),
                ),
                (
                    "current_question",
                    models.ForeignKey(
                        default=game.models.Question.get_default_pk,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="sessions_current_question_in",
                        to="game.question",
                    ),
                ),
                (
                    "left_lifelines",
                    models.ManyToManyField(
                        related_name="sessions_unused", to="game.lifeline"
                    ),
                ),
                (
                    "lifeline_qns",
                    models.ManyToManyField(
                        related_name="sessions_used_lifeline_in", to="game.question"
                    ),
                ),
                (
                    "questions_asked",
                    models.ManyToManyField(
                        related_name="sessions_asked_in",
                        through="game.QuestionOrder",
                        to="game.question",
                    ),
                ),
                (
                    "session_user",
                    models.ForeignKey(
                        on_delete=models.SET(game.models.get_sentinel_user),
                        related_name="initiated_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "used_lifelines",
                    models.ManyToManyField(
                        related_name="sessions_used", to="game.lifeline"
                    ),
                ),
                (
                    "wrong_qn",
                    models.ForeignKey(
                        default=game.models.Question.get_default_pk,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="sessions_wrong_in",
                        to="game.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "session",
                "verbose_name_plural": "sessions",
            },
        ),
        migrations.AddField(
            model_name="questionorder",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="game.session"
            ),
        ),
    ]
