# Generated by Django 4.2.3 on 2023-07-14 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("game", "0003_questionorder_session_questionorder_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="who_added",
            field=models.ForeignKey(
                default=game.models.get_sentinel_user,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="created_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="session_id",
            field=models.CharField(
                default="hgqwDgL1",
                editable=False,
                max_length=8,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
