# Generated by Django 4.2.3 on 2023-07-14 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("game", "0004_alter_session_session_id_alter_session_session_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="session_id",
            field=models.CharField(
                default="eUFpEruE",
                editable=False,
                max_length=8,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="session_user",
            field=models.ForeignKey(
                default=game.models.get_sentinel_user,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="initiated_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
