# Generated by Django 4.2.3 on 2023-07-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0006_alter_session_session_id_alter_session_session_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="session_id",
            field=models.CharField(
                default="f1EKNpFj",
                editable=False,
                max_length=8,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
