# Generated by Django 4.2.3 on 2023-07-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0007_alter_session_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="agreedToRules",
            field=models.BooleanField(default=False, verbose_name="Agreed to T&C"),
        ),
        migrations.AddField(
            model_name="session",
            name="gameOver",
            field=models.BooleanField(default=False, verbose_name="Game over?"),
        ),
        migrations.AlterField(
            model_name="session",
            name="session_id",
            field=models.CharField(
                default="G3ew76JT",
                editable=False,
                max_length=8,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
