# Generated by Django 4.2.3 on 2023-07-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0008_session_agreedtorules_session_gameover_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="session_id",
            field=models.CharField(
                default="kgwvWzAX",
                editable=False,
                max_length=8,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
