# Generated by Django 4.2.3 on 2023-07-17 10:00

from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0009_alter_session_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="prev_level",
            field=models.ForeignKey(
                default=game.models.Level.get_default_pk,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="game.level",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="session_id",
            field=models.CharField(
                default="UncB0JU3",
                editable=False,
                max_length=8,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
