# Generated by Django 4.2.3 on 2023-07-17 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0010_session_prev_level_alter_session_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="level",
            name="level_number",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(-1),
                    django.core.validators.MaxValueValidator(16),
                ],
                verbose_name="Level",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="session_id",
            field=models.CharField(
                default="PU5DlTGQ",
                editable=False,
                max_length=8,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
