# Generated by Django 6.0.2 on 2026-08-13 03:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0014_alter_question_difficulty_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="session",
            old_name="agreedToRules",
            new_name="agreed_to_rules",
        ),
        migrations.RenameField(
            model_name="session",
            old_name="gameOver",
            new_name="game_over",
        ),
    ]
